/**
 * 360 DEGREES CONSULTING - SHARED GLOBAL LAYOUT ENGINE (js/site.js)
 * 
 * What this file does:
 * - Reads settings from js/config.js (SITE_CONFIG).
 * - Injects the shared navbar into <header id="site-header"> on every page.
 * - Injects the shared navy footer into <footer id="site-footer"> on every page.
 * - Manages the mobile hamburger navigation drawer (open/close at <768px).
 * - Highlights the active nav link based on the current page URL.
 * - Reads data-root from <body> so relative paths work from root or subfolders.
 * 
 * How to edit:
 * - To change links or text: edit js/config.js (do not edit this file).
 * - To style the navbar or footer: edit css/style.css.
 */

(function () {
  'use strict';

  function renderSharedLayout() {
    // Safety check: ensure SITE_CONFIG is loaded
    if (typeof SITE_CONFIG === 'undefined') {
      console.error('360 Degrees Consulting: SITE_CONFIG is not defined. Ensure js/config.js is loaded before js/site.js.');
      return;
    }

    // Determine the root prefix (e.g. "" for root files, "../" for subfolders)
    const root = (document.body && document.body.getAttribute('data-root')) || '';

    // Helper to resolve relative URLs with data-root
    function resolve(path) {
      if (!path) return '';
      if (path.startsWith('http://') || path.startsWith('https://') || path.startsWith('mailto:') || path.startsWith('#')) {
        return path;
      }
      return root + path;
    }

    // Determine current page filename (e.g., "about.html", "index.html")
    let currentFile = window.location.pathname.split('/').pop();
    if (!currentFile || currentFile === '') {
      currentFile = 'index.html';
    }

    // =========================================================================
    // 1. INJECT NAVBAR INTO <header id="site-header">
    // =========================================================================
    const header = document.getElementById('site-header');
    if (header) {
      // Ensure the header has the expected editorial class
      if (!header.classList.contains('editorial-header')) {
        header.classList.add('editorial-header');
      }

      // Build desktop navigation items HTML
      const desktopNavItemsHtml = SITE_CONFIG.navItems.map(item => {
        const hasChildren = item.children && item.children.length > 0;
        const isChildActive = hasChildren && item.children.some(child => child.href.endsWith(currentFile));
        const isSelfActive = (item.href === currentFile);
        const isActive = isSelfActive || isChildActive || (item.label === 'Services' && window.location.pathname.includes('/services/'));

        if (hasChildren) {
          const submenuHtml = item.children.map(child => {
            const childActive = child.href.endsWith(currentFile);
            return `<li><a href="${resolve(child.href)}"${childActive ? ' class="active"' : ''}>${child.label}</a></li>`;
          }).join('');

          return `
            <li class="nav-item-dropdown">
              <a href="${resolve(item.href)}"${isActive ? ' class="active"' : ''}>
                ${item.label} <span class="nav-arrow">&#9662;</span>
              </a>
              <ul class="nav-dropdown-menu">
                ${submenuHtml}
              </ul>
            </li>
          `;
        }

        return `<li><a href="${resolve(item.href)}"${isActive ? ' class="active"' : ''}>${item.label}</a></li>`;
      }).join('');

      // Inject the header contents
      header.innerHTML = `
        <div class="container header-inner">
          <a href="${resolve('index.html')}" class="brand-wrap" aria-label="${SITE_CONFIG.name} Home">
            <img src="${resolve('assets/logo.png')}" alt="${SITE_CONFIG.name}" />
          </a>

          <!-- Desktop Navigation -->
          <ul class="editorial-nav">
            ${desktopNavItemsHtml}
            <li><a href="${resolve(SITE_CONFIG.cta.href)}" class="btn-ed btn-ed-primary">${SITE_CONFIG.cta.label}</a></li>
          </ul>

          <!-- Mobile Hamburger Button -->
          <button class="mobile-toggle-btn" id="mobile-toggle" aria-label="Toggle Navigation">☰</button>
        </div>
      `;

      // =======================================================================
      // 2. INJECT MOBILE SLIDE-DOWN DRAWER
      // =======================================================================
      let mobileDrawer = document.getElementById('mobile-drawer');
      if (!mobileDrawer) {
        mobileDrawer = document.createElement('div');
        mobileDrawer.id = 'mobile-drawer';
        mobileDrawer.className = 'mobile-nav-drawer';
        header.insertAdjacentElement('afterend', mobileDrawer);
      }

      const mobileLinksHtml = SITE_CONFIG.navItems.map(item => {
        const hasChildren = item.children && item.children.length > 0;
        const isChildActive = hasChildren && item.children.some(child => child.href.endsWith(currentFile));
        const isSelfActive = (item.href === currentFile);
        const isActive = isSelfActive || isChildActive || (item.label === 'Services' && window.location.pathname.includes('/services/'));

        let itemHtml = `<a href="${resolve(item.href)}" class="mobile-nav-link${isActive ? ' active' : ''}">${item.label} <span>&rarr;</span></a>`;

        if (hasChildren) {
          const sublinks = item.children.map(child => {
            const childActive = child.href.endsWith(currentFile);
            return `<a href="${resolve(child.href)}" class="mobile-subnav-link${childActive ? ' active' : ''}">${child.label}</a>`;
          }).join('');

          itemHtml += `<div class="mobile-subnav-wrap">${sublinks}</div>`;
        }

        return itemHtml;
      }).join('');

      mobileDrawer.innerHTML = `
        ${mobileLinksHtml}
        <a href="${resolve(SITE_CONFIG.cta.href)}" class="btn-ed btn-ed-primary mobile-nav-link">${SITE_CONFIG.cta.label}</a>
      `;

      // Attach click events for hamburger toggle
      const mobileToggle = document.getElementById('mobile-toggle');
      if (mobileToggle && mobileDrawer) {
        mobileToggle.addEventListener('click', () => {
          const isOpen = mobileDrawer.classList.toggle('open');
          mobileToggle.textContent = isOpen ? '✕' : '☰';
        });

        // Close mobile drawer when any link is clicked
        const mobileLinks = mobileDrawer.querySelectorAll('.mobile-nav-link, .mobile-subnav-link');
        mobileLinks.forEach(link => {
          link.addEventListener('click', () => {
            mobileDrawer.classList.remove('open');
            mobileToggle.textContent = '☰';
          });
        });
      }
    }

    // =========================================================================
    // 3. INJECT FOOTER INTO <footer id="site-footer">
    // =========================================================================
    const footer = document.getElementById('site-footer');
    if (footer) {
      if (!footer.classList.contains('editorial-footer')) {
        footer.classList.add('editorial-footer');
      }

      const companyLinksHtml = SITE_CONFIG.footer.companyLinks.map(link => {
        return `<li><a href="${resolve(link.href)}">${link.label}</a></li>`;
      }).join('');

      const legalLinksHtml = SITE_CONFIG.footer.legalLinks.map(link => {
        return `<a href="${resolve(link.href)}">${link.label}</a>`;
      }).join(' &bull; ');

      footer.innerHTML = `
        <div class="container">
          <div class="footer-top-row">
            <div class="footer-brand-info">
              <a href="${resolve('index.html')}" aria-label="${SITE_CONFIG.name} Home">
                <img src="${resolve('assets/logo.png')}" alt="${SITE_CONFIG.name}" loading="lazy" />
              </a>
              <div class="footer-tagline">${SITE_CONFIG.tagline}</div>
              <p>${SITE_CONFIG.description}</p>
            </div>
            <div class="footer-nav-groups">
              <div class="footer-group">
                <h4>Company</h4>
                <ul>
                  ${companyLinksHtml}
                </ul>
              </div>
              <div class="footer-group">
                <h4>Contact</h4>
                <ul>
                  <li><a href="mailto:${SITE_CONFIG.contact.email}">${SITE_CONFIG.contact.email}</a></li>
                  <li><a href="${SITE_CONFIG.contact.linkedin}" target="_blank" rel="noopener noreferrer">LinkedIn Corporate Page</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-bottom-row">
            <p>${SITE_CONFIG.footer.copyright}</p>
            <div class="footer-legal-links">
              ${legalLinksHtml}
            </div>
          </div>
        </div>
      `;
    }
  }

  // Execute synchronously if elements exist in the DOM right now,
  // or wait for DOMContentLoaded if loaded early in <head>.
  if (document.getElementById('site-header') || document.getElementById('site-footer')) {
    renderSharedLayout();
  } else {
    document.addEventListener('DOMContentLoaded', renderSharedLayout);
  }
})();
